version: 2
jobs:
  build:
    machine: true
    environment:
      - CGO_ENABLED: "0"
        GOOS: "linux"
        GOARCH: "amd64"
        GOPATH: "$HOME/go"
        GS_WD: "$HOME/go/src/github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
    steps:
      - checkout
      - run:
          name: Copy source to right location
          command: |
            mkdir -p $HOME/go/src/github.com/$CIRCLE_PROJECT_USERNAME
            cp -rf $HOME/$CIRCLE_PROJECT_REPONAME $HOME/go/src/github.com/$CIRCLE_PROJECT_USERNAME
      # tests
      - run:
          name: go test
          command: |
            cd $GS_WD
            go test -v ./...
      - run:
          name: go build
          command: |
            cd $GS_WD
            go build -a -v -tags netgo -ldflags "-w"
